from __future__ import annotations

import copy
import json
import os
import tempfile
from pathlib import Path
from typing import Any

from app.core.config import PROJECT_ROOT
from app.desktop.secret_store import read_secret, write_secret


LOCAL_APP_ROOT = PROJECT_ROOT / "data" / "local_app"
CONFIG_PATH = LOCAL_APP_ROOT / "config.json"
RUNTIME_ENV_PATH = LOCAL_APP_ROOT / "runtime.env"
SECRETS_PATH = LOCAL_APP_ROOT / "secrets.dpapi"

DEFAULT_CONFIG: dict[str, Any] = {
    "version": 1,
    "text": {
        "provider": "deepseek-compatible",
        "model": "deepseek-v4-pro",
        "base_url": "https://api.deepseek.com",
        "capability": "text-only",
    },
    "vision": {
        "enabled": True,
        "provider": "openai-compatible",
        "model": "qwen2.5-vl:7b",
        "base_url": "http://127.0.0.1:11434/v1",
    },
    "memory": {
        "enabled": True,
        "backend": "qdrant",
        "url": "http://127.0.0.1:6333",
        "collection": "hutao_memories",
        "embedding_model": "BAAI/bge-m3",
        "auto_save": False,
    },
    "persona": {
        "id": "hutao_v1",
        "display_name": "胡桃",
        "voice_profile": "hutao_e15",
    },
    "computer_control": {
        "mode": "confirm",
        "allowed_apps": [],
        "allow_shell": False,
        "allow_file_delete": False,
    },
}


def _merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _merge(result[key], value)
        else:
            result[key] = value
    return result


def load_config() -> dict[str, Any]:
    if not CONFIG_PATH.is_file():
        return copy.deepcopy(DEFAULT_CONFIG)
    try:
        raw = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return copy.deepcopy(DEFAULT_CONFIG)
    if not isinstance(raw, dict):
        return copy.deepcopy(DEFAULT_CONFIG)
    return _merge(DEFAULT_CONFIG, raw)


def save_config(payload: dict[str, Any]) -> dict[str, Any]:
    merged = merge_config(payload)
    LOCAL_APP_ROOT.mkdir(parents=True, exist_ok=True)
    _atomic_write(CONFIG_PATH, json.dumps(merged, ensure_ascii=False, indent=2) + "\n")
    _write_runtime_env(merged)
    return merged


def merge_config(payload: dict[str, Any], *, persist_secrets: bool = True) -> dict[str, Any]:
    current = load_config()
    clean_payload = copy.deepcopy(payload)
    for section in ("text", "vision"):
        incoming = clean_payload.get(section)
        existing = current.get(section)
        if isinstance(incoming, dict):
            incoming.pop("api_key_configured", None)
            api_key = str(incoming.pop("api_key", "") or "").strip()
            if api_key and persist_secrets:
                write_secret(SECRETS_PATH, section, api_key)
        if isinstance(existing, dict):
            existing.pop("api_key", None)
    merged = _merge(current, clean_payload)
    merged["version"] = 1
    return merged


def public_config(config: dict[str, Any] | None = None) -> dict[str, Any]:
    value = copy.deepcopy(config or load_config())
    for section in ("text", "vision"):
        if isinstance(value.get(section), dict):
            value[section].pop("api_key", None)
            value[section]["api_key_configured"] = bool(read_secret(SECRETS_PATH, section))
    return value


def secret_for(config: dict[str, Any], section: str, fallback: str = "") -> str:
    return read_secret(SECRETS_PATH, section).strip() or fallback


def _write_runtime_env(config: dict[str, Any]) -> None:
    text = config.get("text", {})
    if not isinstance(text, dict):
        return
    lines = [
        "# Generated by the local desktop settings page. Do not commit this file.",
        f"MODEL_PROVIDER=deepseek",
        f"MODEL_NAME={_env_value(text.get('model'), 'deepseek-v4-pro')}",
        f"MODEL_BASE_URL={_env_value(text.get('base_url'), 'https://api.deepseek.com')}",
        f"SEMANTIC_MEMORY_ENABLED={'true' if config.get('memory', {}).get('enabled') else 'false'}",
    ]
    _atomic_write(RUNTIME_ENV_PATH, "\n".join(lines) + "\n")


def _env_value(value: object, default: str) -> str:
    raw = str(value if value is not None else default).replace("\r", "").replace("\n", "")
    return raw.replace('"', "")


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary_name, path)
    finally:
        Path(temporary_name).unlink(missing_ok=True)
